[tool.black]
line-length = 120

# see .flake8 for flake8 config

[tool.isort]
profile="black"
line_length = 120
# make compatible with black
multi_line_output=3
include_trailing_comma='True'
force_grid_wrap=0
use_parentheses='True'
ensure_newline_before_comments='True'
known_first_party=''
known_third_party=''